### ISSUE TITLE
Tip: you could simply use maven for this

### ISSUE THREAD

**Issue by adael** [foundeo/maven-command#3]
This command seems to not download all dependencies propertly. Also you could get all your dependencies correctly by using maven:

`mvn dependency:copy-dependencies -DoutputDirectory=lib/`

This `box maven` command is a great idea anyway. I hope everyone understands this comment as constructive as possible.

Kind regards,

**Comment by pfreitag** [comment]
Thanks @adael - yes there are some cases where it is not finding second level dependencies, that needs to be ironed out still. Aware that you can just use `mvn` command, the idea for this was to be able to interact with maven programmatically.

**Comment by pfreitag** [comment]
@adael  I've added known issues to the readme in commit: 387801d5e88c44229cba72a206957162f7d661b1
